// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: intend.proto
#ifndef GRPC_intend_2eproto__INCLUDED
#define GRPC_intend_2eproto__INCLUDED

#include "intend.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace intend {

class Intend final {
 public:
  static constexpr char const* service_full_name() {
    return "intend.Intend";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::intend::IntendRequest, ::intend::IntendReply>> IntendChat(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::intend::IntendRequest, ::intend::IntendReply>>(IntendChatRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::intend::IntendRequest, ::intend::IntendReply>> AsyncIntendChat(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::intend::IntendRequest, ::intend::IntendReply>>(AsyncIntendChatRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::intend::IntendRequest, ::intend::IntendReply>> PrepareAsyncIntendChat(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::intend::IntendRequest, ::intend::IntendReply>>(PrepareAsyncIntendChatRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::intend::RealtimeInfo, ::intend::PolicyInfo>> IntChat(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::intend::RealtimeInfo, ::intend::PolicyInfo>>(IntChatRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::intend::RealtimeInfo, ::intend::PolicyInfo>> AsyncIntChat(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::intend::RealtimeInfo, ::intend::PolicyInfo>>(AsyncIntChatRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::intend::RealtimeInfo, ::intend::PolicyInfo>> PrepareAsyncIntChat(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::intend::RealtimeInfo, ::intend::PolicyInfo>>(PrepareAsyncIntChatRaw(context, cq));
    }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::intend::IntendRequest, ::intend::IntendReply>* IntendChatRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::intend::IntendRequest, ::intend::IntendReply>* AsyncIntendChatRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::intend::IntendRequest, ::intend::IntendReply>* PrepareAsyncIntendChatRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::intend::RealtimeInfo, ::intend::PolicyInfo>* IntChatRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::intend::RealtimeInfo, ::intend::PolicyInfo>* AsyncIntChatRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::intend::RealtimeInfo, ::intend::PolicyInfo>* PrepareAsyncIntChatRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReaderWriter< ::intend::IntendRequest, ::intend::IntendReply>> IntendChat(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::intend::IntendRequest, ::intend::IntendReply>>(IntendChatRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::intend::IntendRequest, ::intend::IntendReply>> AsyncIntendChat(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::intend::IntendRequest, ::intend::IntendReply>>(AsyncIntendChatRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::intend::IntendRequest, ::intend::IntendReply>> PrepareAsyncIntendChat(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::intend::IntendRequest, ::intend::IntendReply>>(PrepareAsyncIntendChatRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::intend::RealtimeInfo, ::intend::PolicyInfo>> IntChat(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::intend::RealtimeInfo, ::intend::PolicyInfo>>(IntChatRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::intend::RealtimeInfo, ::intend::PolicyInfo>> AsyncIntChat(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::intend::RealtimeInfo, ::intend::PolicyInfo>>(AsyncIntChatRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::intend::RealtimeInfo, ::intend::PolicyInfo>> PrepareAsyncIntChat(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::intend::RealtimeInfo, ::intend::PolicyInfo>>(PrepareAsyncIntChatRaw(context, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientReaderWriter< ::intend::IntendRequest, ::intend::IntendReply>* IntendChatRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::intend::IntendRequest, ::intend::IntendReply>* AsyncIntendChatRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::intend::IntendRequest, ::intend::IntendReply>* PrepareAsyncIntendChatRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::intend::RealtimeInfo, ::intend::PolicyInfo>* IntChatRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::intend::RealtimeInfo, ::intend::PolicyInfo>* AsyncIntChatRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::intend::RealtimeInfo, ::intend::PolicyInfo>* PrepareAsyncIntChatRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_IntendChat_;
    const ::grpc::internal::RpcMethod rpcmethod_IntChat_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status IntendChat(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::intend::IntendReply, ::intend::IntendRequest>* stream);
    virtual ::grpc::Status IntChat(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::intend::PolicyInfo, ::intend::RealtimeInfo>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_IntendChat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_IntendChat() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_IntendChat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IntendChat(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::intend::IntendReply, ::intend::IntendRequest>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestIntendChat(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::intend::IntendReply, ::intend::IntendRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_IntChat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_IntChat() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_IntChat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IntChat(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::intend::PolicyInfo, ::intend::RealtimeInfo>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestIntChat(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::intend::PolicyInfo, ::intend::RealtimeInfo>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_IntendChat<WithAsyncMethod_IntChat<Service > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_IntendChat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_IntendChat() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_IntendChat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IntendChat(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::intend::IntendReply, ::intend::IntendRequest>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_IntChat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_IntChat() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_IntChat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IntChat(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::intend::PolicyInfo, ::intend::RealtimeInfo>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace intend


#endif  // GRPC_intend_2eproto__INCLUDED
